config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions, only: %i[index show new create edit update destroy] do
    resources :answers, expect: %i[index show new]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end

  root 'welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
  # Связь с таблицей Question 1:М Answer
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show edit update destroy]

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
    @questions = @questions.decorate
  end

  def show
    @question = @question.decorate
    # Ищет question по id
    # Инициализируем новый несохранённый answer привязанный к question
    @answer = @question.answers.build
    # Массив со всеми answers сортированный по дате
    @pagy, @answers = pagy @question.answers.order(created_at: :desc), items: 2
    # Массив со всеми answers сортированный по дате 2 способ
    # @answers = Answer.where(question_id: @question.id).order created_at: :desc
    @answers = @answers.decorate
  end

  def new
    # Инициализируем новый несохранённый question
    @question = Question.new
  end

  def create
    # render plain: params - Отображает отправленные данные
    # Сохраняет question в БД
    @question = Question.new question_params
    if @question.save
      flash[:success] = 'Question created!'
      redirect_to questions_path
    else
      render :new
    end
  end

  # Ищет question по id
  def edit; end

  def update
    # Ищет question по id
    # Изменяет question в БД
    if @question.update question_params
      flash[:success] = 'Question update!'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    # Ищет question по id
    # Удаляет question из БД
    @question.destroy
    flash[:success] = 'Question deleted!'
    redirect_to questions_path
  end

  private

  # Выдаёт ошибку если не находит question
  def set_question!
    # Ищет question по id
    @question = Question.find params[:id]
  end

  # Фильтрация params для question
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/views/questions/_form.html.erb
<%# Проверка пользовательского ввода %>
<%= render 'shared/errors', object: @question %>

<%# Форма создания и редактирования нового вопроса %>
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%# Проверка пользовательского ввода на клиенте и на сервере %>
      <%= f.text_field :title, required: true, minlenght: 2, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%# Проверка пользовательского ввода на сервере %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Submit question', class: 'btn btn-success' %>
  <%= link_to 'Back', questions_path, class: 'btn btn-secondary' %>
<% end %>

app/views/questions/edit.html.erb
<%# title %>
<% provide :page_title, 'Edit question' %>

<%# header меню %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Edit question</h1>

<%# Форма создания и редактирования нового вопроса %>
<%= render 'form' %>

app/views/questions/index.html.erb
<%# title %>
<% provide :page_title, 'Questions' %>

<%# header меню %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<%# Ссылка на форму создания и редактирования нового вопроса %>
<%= link_to 'Ask a new question', new_question_path, class: 'btn btn-outline-dark mb-4' %>

<%= pagination @pagy %>

<%# Карточки с вопросами %>
<% @questions.each do |question| %>
  <article class="card my-4">
    <div class="card-body">
      <h4><%= question.title %></h4>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%# strip_tags удаляет все html теги %>
          <%# truncate сокращаем длину question.body до 100 символов %>
          <%= truncate strip_tags(question.body), length: 100, omission: '... (continued)' %>
        </p>
      </section>

      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-warning' %>
      <%= link_to 'Delete', question_path(question), data: { method: :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </article>
<% end %>

<%= pagination @pagy %>

app/views/questions/new.html.erb
<%# title %>
<% provide :page_title, 'New question' %>

<%# header меню %>
<% currently_at 'Questions' %>

<h1 class="mb-4">New question</h1>

<%# Форма создания и редактирования нового вопроса %>
<%= render 'form' %>

app/views/questions/show.html.erb
<%# title %>
<% provide :page_title, @question.title %>

<%# header меню %>
<% currently_at 'Questions' %>

<%# Вопрос %>
<div>
  <h1 class="mb-4"><%= @question.title %></h1>

  <time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
  </time>

  <div class="lead my-3">
    <%# Разрешаем обрабатывать безопасный html %>
    <%= sanitize @question.body %>
  </div>
</div>

<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-primary' %>
<%= link_to 'Delete', question_path(@question), data: { method: :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to 'Back', questions_path, class: 'btn btn-secondary' %>

<hr class="my-3">

<h2>Write your answer</h2>

<%# Форма создания ответа для конкретного вопроса %>
<%= render 'answers/form' %>

<hr class="my-3">

<h2 class="mt-3">Answers</h2>

<%# Ответы %>
<%# partial: 'answers/answer' - рендерим _answer %>
<%# collection: @answers - рендерим именно коллекцию %>
<%# as: :answer - имя элементов коллекции %>
<%# locals: {question: @question} - передаём в partial _answer переменную @question %>
<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question} %>

<%= pagination @pagy %>