config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions, only: %i[index show new create edit update destroy] do
    resources :answers, expect: %i[index show new]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end

  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  # Связь с таблицей Question 1:М Answer
  belongs_to :question

  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # Для работы dom_id
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create

  def create
    # render plain: params - Отображает отправленные данные
    # Ищет question из таблицы Answer по question_id
    # Сохраняет answer в БД
    @answer = @question.answers.build answer_params
    if @answer.save
      flash[:success] = 'Answer created!'
      redirect_to question_path(@question)
    else
      @question = @question.decorate
      # Массив со всеми answers сортированный по дате
      @pagy, @answers = pagy @question.answers.order(created_at: :desc)
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  # Ищет question из таблицы Answer по question_id
  def edit; end

  def update
    # Ищет question из таблицы Answer по question_id
    # Изменяет answer в БД
    if @answer.update answer_params
      flash[:success] = 'Answer update!'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def destroy
    # Ищет question из таблицы Answer по question_id
    # Удаляет answer из БД
    @answer.destroy
    flash[:success] = 'Answer deleted!'
    redirect_to question_path(@question)
  end

  private

  # Выдаёт ошибку если не находит question
  def set_question!
    # Ищет question по таблице Answer по question_id
    @question = Question.find params[:question_id]
  end

  def set_answer!
    # Ищет answer из конкретного question по id
    @answer = @question.answers.find params[:id]
  end

  # Фильтрация params для answer
  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>

    <%= link_to 'Edit', edit_question_answer_path(question, answer), class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
                data: { method: :delete, confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%# Проверка пользовательского ввода %>
<%= render 'shared/errors', object: @answer %>

<%# Форма создания ответа для конкретного вопроса %>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<%# title %>
<% provide :page_title, 'Edit answer' %>

<%# header меню %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Edit answer</h1>

<%# Проверка пользовательского ввода %>
<%= render 'shared/errors', object: @answer %>

<%# Форма создания ответа для конкретного вопроса %>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer", class: 'btn btn-primary' %>
  <%= link_to 'Back', question_path(@question), class: 'btn btn-secondary' %>
<% end %>